### ISSUE TITLE
Right touchpad sticking after eating (in game) food 

### ISSUE THREAD

**Issue by Valadon** [jrbudda/minecrift#111]
When I am holding a food item in my hand (have tested with apples and bread) and then eat it by holding down the right touchpad button it seems to get stuck. In other words I try to eat 1 bread and instead end up eating the whole stack of bread because the touchpad button acts as if it is stuck down. If I slide over on the left touch pad and select another item, a block of dirt for instance, it will then start placing dirt blocks everywhere I swing my right hand. It will stop if I hit the touch pad button a few times. 

It acts like the button is getting stuck down but this only happens when I eat a food item in minecraft, it has never happened in any other game or doing anything else besides eating in minecraft. I haven't done a lot of testing since I have run out of food! but it has happened all 3 times that I tried to eat. 

Let me know if you need any other info.

Thanks for the great mod!

**Comment by jrbudda** [comment]
I'll look into it. Thank's for the detailed report I think I know where the problem may be.

**Comment by Dung3onlord** [comment]
I just wanted to say that i got a similar issue. For me regardless of what i do it seems like the button get stucked and so i keep on placing blocks and opening chests/doors. It is worth saying that with other games/app that uses the trackpad this doesn't seem to be the case

**Comment by jrbudda** [comment]
I took a stab at fixing this in v21, not sure if I got it all the way. Please test.

**Comment by Valadon** [comment]
I did a quick test and it looks like it is fixed...or I was just too full and it wouldn't let me eat anymore. However I also tried switching to another item after I ate and it didn't act like it was stuck down. I.e it didn't start placing dirt everywhere I looked. So I would say that early test point to it being fixed, i'll test some more tomorrow night. 

However; several times when I first loaded into the game it acted like my right trigger was stuck, and my guy was swinging his sword none stop until I hit the trigger again which seemed to unstick it.

**Comment by jrbudda** [comment]
yeaa i noticed that... not sure of the cause, something about clicking on the menu, didnt fix before release because its easy to stop as you found.

**Comment by Dung3onlord** [comment]
ok great i will give it a shot....unfortunately got some other " more serious issue"  with the 22. also posted them
thanks for the great work

----Messaggio originale----

Da: "jrbudda" notifications@github.com

Data: 23-giu-2016 17.26

A: "jrbudda/minecrift"minecrift@noreply.github.com

Cc: "Dung3onlord"dungeonlord@libero.it, "Comment"comment@noreply.github.com

Ogg: Re: [jrbudda/minecrift] Right touchpad sticking after eating (in game) food (#111)

I took a stab at fixing this in v21, not sure if I got it all the way. Please test.
