### ISSUE TITLE
The entire sky/world flickers when holding an enchanted item

### ISSUE THREAD

**Issue by slicedlime** [jrbudda/minecrift#193]
I've been making an LP series on Vivecraft and just ran into a very significant issue. Whenever I equip an enchanted weapon or tool, the entire sky starts flickering intensely - bad enough to be really unpleasant. In the overworld this can be avoided by simply going underground - there only the hotbar icons flash. In the nether, however, the entire world flashes and there's no escaping it as long as you have an enchanted weapon out.

I can't show footage of the problem either, because the window rendered on the monitor (which is what I'm recording) is working fine - it's only a problem in the Vive headset.

**Comment by Techjar** [comment]
Are you using the undistorted mirror?

**Comment by slicedlime** [comment]
No - I hadn't seen that setting. Dual (1/3).

**Comment by Techjar** [comment]
Huh, okay then. Not sure why you're using 1/3 as it'll look pretty crappy on the recording. I have no idea what's going on, will have to test.

**Comment by slicedlime** [comment]
Good question. Like I said, I haven't seen that setting before, been a while since I tinkered with the settings, so it's just been left on whatever it was.

**Comment by jrbudda** [comment]
Does it change if you toggle fsaa?

**Comment by slicedlime** [comment]
Sorry, took me a while before I had the time to fire it back up. Yes, it did indeed go away if I switched off FSAA.

**Comment by jrbudda** [comment]
is it fixed in this build? i couldnt reproduce it.

[vivecraft-1.7.10-Vivecraft-jrbudda31-installer.exe.zip](https://github.com/jrbudda/minecrift/files/392288/vivecraft-1.7.10-Vivecraft-jrbudda31-installer.exe.zip)

**Comment by slicedlime** [comment]
I didn't have time to test that specific build I'm afraid. I did test v3 of the 1.10.2 line and couldn't reproduce it there.

**Comment by donkers** [comment]
I have also been experiencing flickering, in the nether at least, and it is indeed resolved by disabling FSAA (soooooo glad I found this infos).

I can confirm that it still persists in both build 1.7.10 jrbudda31 and 31r1. And I note that the flickering only occurs in the right eye.

If it helps I am running with forge 1.7.10-10.13.4.1614 and the following mods:
appliedenergistics2-rv3-beta-6.jar
BetterBuildersWands-0.6.1-1.7.10r80+358ee26.jar
BigReactors-0.4.3A.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel-2.9.5.11.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
EnderCore-1.7.10-0.2.0.36_beta.jar
EnderIO-1.7.10-2.3.0.428_beta.jar
Ex-Nihilo-1.38-49.jar
extrautilities-1.2.12.jar
fastcraft-1.23.jar
ImmersiveEngineering-0.7.7.jar
Mantle-1.7.10-0.3.2b.jar
mcjtylib-1.8.1.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
natura-1.7.10-2.2.0.1.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
rftools-4.23.jar
SimplyJetpacks-MC1.7.10-1.5.3.jar
SolarFlux-1.7.10-0.8b.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.1.2-240.jar

If I can help with any more information or testing just ask. Keep up the good work. Thanks

**Comment by slicedlime** [comment]
Oh, to add that info from my perspective as well - I was running with forge, but without any other mods.

**Comment by jrbudda** [comment]
i tested this pretty thoroughly in vanilla so it must be something caused by forge... which makes its a pain to troubleshoot.  Will take a swing at it tho.

Does it always happen in the nether? does it change depending on what youre holding or if you have a menu open?

**Comment by donkers** [comment]
I find it almost always happens in the nether. Sometimes I find a spot (x,y,z location) that if I face a certain direction it stops, but move around for a minute and it is bound to come back.
