### ISSUE TITLE
[1.12.1] Block not Tesselating crash

### ISSUE THREAD

**Issue by XiloTheOdd** [jrbudda/minecrift#285]
so i decided to see if thermal expansion's latest mod worked with vivecraft, twas one of my favorite mods to use way back. it feeds back a block not tessellating error. this is the first time i've ever encountered this problem so its new to me.

https://pastebin.com/Vfmb4VeM

NEW: https://pastebin.com/Jidp8ivY

i asked on thermal expansion's page already and they said it was probably on the vivecraft end of things.

if any other info is needed i'll happily supply it and gladly accept any explaination as to why this might be happening and ways around it.

**Comment by Techjar** [comment]
This is already fixed in an unreleased build.

**Comment by XiloTheOdd** [comment]
oh cool! cant wait then! :)

**Comment by Techjar** [comment]
We just released 3r4 which fixes this. The menu world won't load, but at least it won't crash anymore. Unfortunately there's nothing we can do to fix that as some mods just do unpredictable things to the BlockModelRenderer.

**Comment by XiloTheOdd** [comment]
hmm im on the latest one and its still crashing after it generates the menu world (i watched forge and the folder at the same time.) i've removed all other compatible mods jsut to make sure it wasnt a mods not playing nice issue, and it seems to just be thermal expansion and thermal dynamics triggering it still. is there anything i need to do special to get the menu world to basically not happen?

new log: https://pastebin.com/Jidp8ivY

**Comment by jrbudda** [comment]
you're sure you're on 1.12.1 v3r4?

**Comment by XiloTheOdd** [comment]
yep positive, if it helps i dont mind doing a full folder wipe and reinstalling, havnt gotten to trying that yet.

edit: went ahead with the full wipe, issue persists, only loaded JEI and the CofH Mods this time around, the ones to trigger it are still Expansion and Dynamics. updated new log with new data, same link.

**Comment by jrbudda** [comment]
try the just-uploaded 3r5

**Comment by XiloTheOdd** [comment]
yep it loaded and it told me im a moron xD. forgot codechickenlib. i cant believe i did that.

**Comment by Techjar** [comment]
Yeah, we had a bit of a VCS error and the build wasn't actually up to date.

**Comment by XiloTheOdd** [comment]
alright, menu generated a world, but now its functioning up to that point.

**Comment by XiloTheOdd** [comment]
alright played for a bit and no more issues! thanks so much for helpin out. enjoying the VR controls and the immersion it brings, if i encounter anything else i'll be sure to let you guys know! :)
